import 'package:team1/features/product_management/data/datasources/product_api_service.dart';
import 'package:team1/features/product_management/data/models/product_model.dart';
import 'package:team1/features/product_management/domain/entities/product.dart';
import 'package:team1/features/product_management/domain/repositories/product_repository.dart';

class ProductRepositoryImpl implements ProductRepository {
  final ProductApiService remoteDataSource;

  ProductRepositoryImpl(this.remoteDataSource);

  @override
  Future<List<Product>> getAllProducts() async {
    final productModels = await remoteDataSource.getAllProducts();
    return productModels.map((model) => model as Product).toList();
  }

  @override
  Future<Product> createProduct(Product product) async {
    final productModel = ProductModel(
      id: 0, // ID will be generated by the backend
      name: product.name,
      description: product.description,
      price: product.price,
      discountPrice: product.discountPrice,
      stockQuantity: product.stockQuantity,
      categoryId: product.categoryId,
      isActive: product.isActive,
      createdAt: DateTime.now(),
      mainImageFile: product.mainImageFile,
      galleryImageFiles: product.galleryImageFiles,
    );
    final createdModel = await remoteDataSource.createProduct(productModel);
    return createdModel as Product;
  }

  @override
  Future<Product> updateProduct(Product product) async {
    final productModel = ProductModel(
      id: product.id,
      name: product.name,
      description: product.description,
      price: product.price,
      discountPrice: product.discountPrice,
      stockQuantity: product.stockQuantity,
      categoryId: product.categoryId,
      isActive: product.isActive,
      createdAt: product.createdAt,
      updatedAt: DateTime.now(), // Update the updated_at timestamp
      mainImageFile: product.mainImageFile,
      galleryImageFiles: product.galleryImageFiles,
    );
    final updatedModel = await remoteDataSource.updateProduct(productModel);
    return updatedModel as Product;
  }

  @override
  Future<void> deleteProduct(int id) async {
    await remoteDataSource.deleteProduct(id);
  }
}
