import 'package:team1/features/category_management/data/datasources/category_api_service.dart';
import 'package:team1/features/category_management/data/models/category_model.dart';
import 'package:team1/features/category_management/domain/entities/category.dart';
import 'package:team1/features/category_management/domain/repositories/category_repository.dart';

class CategoryRepositoryImpl implements CategoryRepository {
  final CategoryApiService remoteDataSource;

  CategoryRepositoryImpl(this.remoteDataSource);

  @override
  Future<List<Category>> getAllCategories() async {
    final categoryModels = await remoteDataSource.getAllCategories();
    return categoryModels.map((model) => model as Category).toList();
  }

  @override
  Future<Category> createCategory(Category category) async {
    final categoryModel = CategoryModel(
      id: 0, // ID will be generated by the backend
      name: category.name,
      description: category.description,
      imageUrl: category.imageUrl,
      parentCategoryId: category.parentCategoryId,
      isActive: category.isActive,
      createdAt: DateTime.now(),
    );
    final createdModel = await remoteDataSource.createCategory(categoryModel);
    return createdModel as Category;
  }

  @override
  Future<Category> updateCategory(Category category) async {
    final categoryModel = CategoryModel(
      id: category.id,
      name: category.name,
      description: category.description,
      imageUrl: category.imageUrl,
      parentCategoryId: category.parentCategoryId,
      isActive: category.isActive,
      createdAt: category.createdAt, // Keep original creation date
    );
    final updatedModel = await remoteDataSource.updateCategory(categoryModel);
    return updatedModel as Category;
  }

  @override
  Future<void> deleteCategory(int id) async {
    await remoteDataSource.deleteCategory(id);
  }
}
